package com.example.demo.model;

public class Likecount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likecount.user_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likecount.comment_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    private Long comment_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likecount.user_id
     *
     * @return the value of likecount.user_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likecount.user_id
     *
     * @param user_id the value for likecount.user_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likecount.comment_id
     *
     * @return the value of likecount.comment_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    public Long getComment_id() {
        return comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likecount.comment_id
     *
     * @param comment_id the value for likecount.comment_id
     *
     * @mbg.generated Thu Sep 05 21:37:49 CST 2019
     */
    public void setComment_id(Long comment_id) {
        this.comment_id = comment_id;
    }
}